CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(30) UNIQUE NOT NULL,
    password VARCHAR2(30) NOT NULL
);

CREATE TABLE Movies (
    movie_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(100) NOT NULL,
    genre VARCHAR2(50),
    duration NUMBER
);

CREATE TABLE Theaters (
    theater_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    location VARCHAR2(100)
);

CREATE TABLE ShowTimes (
    showtime_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id NUMBER REFERENCES Movies(movie_id),
    theater_id NUMBER REFERENCES Theaters(theater_id),
    show_time TIMESTAMP
);

CREATE TABLE Bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER REFERENCES Users(user_id),
    showtime_id NUMBER REFERENCES ShowTimes(showtime_id),
    num_tickets NUMBER,
    total_amount NUMBER
);
